### PR TITLE
Add automatic bone orientation to blender import

### PR DESCRIPTION
**Pull request by jjoshpoland**
This is a minor change that allows for more easily editing the animations in Blender.

I ran the latest version of the script this time, this is the only piece that I think is missing.

### CODE REVIEW

**Comment by scotmcp** [comment]
What does that option do?
I know what the docs say, but I want to know what it's fixing that is wrong.

Thanks

**Comment by jjoshpoland** [comment]
When Blender imports the bones from these FBX assets, they are imported at an angle, like this:
image

Vs when that option is added, the correct orientation is found:
image

Side note, the 2H Sword animation I imported here actually had the correct applied rotation before Blender script import, so it might be good to have a check to see if the rotation is correct before doing any more rotation on the import script.

**Comment by scotmcp** [comment]
I think that's a mostly cosmetic change...the animations themselves behave as they should.

I'll need to do some testing to make sure it doesn't have a downstream impact.

Thanks,
Scot

**Comment by jjoshpoland** [comment]
They behave as they should, but if you want to edit them in blender, that can be an issue. So its not for everyone, but I think its worthwhile. Thanks for considering.

**Comment by scotmcp** [comment]
Merged with main, thank you for your contribution!!

Scot

**Pull request merged**
